### ISSUE TITLE
[FEATURE REQUEST] Optional Leaderboard

### ISSUE THREAD

**Issue by rshrc** [ankiiitraj/doto-client#1]
### Giving the user the choice to opt-out of leaderboard rating

Possible Approaches to the solution:
- Display **Anonymous** in place of users who opted out. Might be easier so that data is not out of sync
- Add to the leaderboard only if the user subscribes to the feature. Remove the member when generating the rank list. 

Happy to discuss more possible solutions.

**Comment by ankiiitraj** [comment]
The function has been add in the last commit!

**Comment by rshrc** [comment]
Absolute beauty 🚩🚩
