### ISSUE TITLE
Repeated question

### ISSUE THREAD

**Issue by arjun-khanduri** [ankiiitraj/doto-client#18]
In the Arrays section, the problem labelled 'Kadane's Algorithm' and the one labelled 'find largest sum contiguous subarray' lead to the same link (which makes sense because the latter question is solved with the help of Kadane's Algorithm).

**Comment by prakalpshakya31** [comment]
Actually Love Babbar Bhaiya repeated some questions for their importance level.

**Comment by arjun-khanduri** [comment]
Noted @prakalpshakya31 😄
