### ISSUE TITLE
Spelling Error (Trie) 😄 

### ISSUE THREAD

**Issue by Jarvis-Yeah** [ankiiitraj/doto-client#27]
Hey! there, 
I know it's silly but I'd just found a spelling mistake in your website. It'll great if you look into it. 
I'd attached the screenshot also. 

Nice Work ❤️ 🔥 
![image](https://user-images.githubusercontent.com/89836460/135334886-cc62d7f5-65fe-415a-93b3-1bee51df1c9e.png)

**Comment by ankiiitraj** [comment]
Trie seems to be correct!
![Screenshot 2021-09-30 at 1 09 09 AM](https://user-images.githubusercontent.com/48787278/135337175-e5c49a38-a3c4-4e0d-996b-b5095d5b3194.png)
