### ISSUE TITLE
Make the current expanded topic stick

### ISSUE THREAD

**Issue by ankiiitraj** [ankiiitraj/doto-client#36]
Right now if we have expanded some topics and scroll down the topic tab goes outside the window and to now unexpand the topic we need to scroll up.

A better UX would be to stick the topic tab at the top while scrolling questions from that topic.

feel free to ask for clarifications.

**Comment by jahtomini** [comment]
I'll love to work on this

**Comment by ankiiitraj** [comment]
please go adhead!
